customDomain:
  domainName: bo-api.dev.partner-portal.inhouse-sony-startup-acceleration-program.com
  certificateName: "dev.partner-portal.inhouse-sony-startup-acceleration-program.com"

lambda:
  memorySize: 2048
  logRetentionInDays: 365

events:
  enabled: true
