customDomain:
  domainName: api.sqa.partner-portal.inhouse-sony-startup-acceleration-program.com
  certificateName: "sqa.partner-portal.inhouse-sony-startup-acceleration-program.com"

lambda:
  memorySize: 2048
  logRetentionInDays: 365

events:
  enabled: true
